### ISSUE TITLE
Import annotations

### ISSUE THREAD

**Issue by phildenhoff** [phildenhoff/logseq-raindrop#1]
Import annotations as pages a-la [c6p/logseq-hypothesis](https://github.com/c6p/logseq-hypothesis).

- Annotations are imported per-URL
- Operation must be idempotent
  - When operation is run on an existing page, and there are new annotations, new annotations are added to the existing page
- Imported pages should have an "import version" so that we can up the version over time
- Use Raindrop IDs for URLs ("raindrops") at the page-level and for annotations at the block-level
- Annotation import allows users to customize formatting
  - Use Plugin settings
  - If the formatting method is changed, _all existing blocks should be updated_ [1]
  
[1]: That means we need some generic identifier for pages imported via `logseq-raindrop` — although looking for pages which include `ls_raindrop_annotation_version` (or something) would work

**Comment by edwarddarrah** [comment]
@phildenhoff, I am having trouble getting this to work. Is there a quick video on the import works? I keep getting the error message, "No URLs found in the current selection. X Make sure they start with https://"


Thanks,
Ed

**Comment by edwarddarrah** [comment]
I got this to work. I realized the workflow to save links directly into Raindrop from Logseq. Is it possible to create a search for links stored in Raindrop to pull into a Logseq block? This would look similar to how the Zotero plugin works.

**Comment by phildenhoff** [comment]
Hi @edwarddarrah, yes. The master branch of this repo already has that behaviour — it just hasn't been released. I'm not 100% happy with how importing works yet and haven't given it the time to compare to alternatives like Zotero to see how they do it. I don't want to release buggy software if I don't have to.

If you'd like to test it out, you can pull the repo & test it out in dev mode, but that requires some setup & config know-how. It's not generally easy.

**Comment by phildenhoff** [comment]
This is included in the new v0.0.3 release — @lxxself and @edwarddarrah, try it out and let me know how it works. I'm open to suggestions :)

**Comment by edwarddarrah** [comment]
@phildenhoff Awswome, thank you for the update.

**Comment by lxxself** [comment]
Great. Thank you for your development.
