### ISSUE TITLE
feature request: import tags

### ISSUE THREAD

**Issue by feigaoxyz** [phildenhoff/logseq-raindrop#12]
import the tags of url in Raindrop into logseq as page property `tags::`

**Comment by phildenhoff** [comment]
Can you clarify a bit more how you see this working?

- would you expect tags to show up in Logseq exactly as they are in Raindrop? (e.g. a #work Raindrop tag shows up as [[work]] or #work)
- OR, would you expect Raindrop tags to show up in Logseq with a prefix — e.g. #work in Raindrop becomes [[logseq-raindrop/work]] or #myCustomRaindropTag-work, the same thing we do with page titles.

maybe that should just be configurable?

For the name `tags::`, I'd _probably_ want to name space it like `raindrop-tags::` — do you _specifically_ want to be able to merge these with all of your other `tags::`?

Another thing to consider is, if that is configurable, how we keep it in sync. If you change the "tag" label, does the plugin go through _all_ logseq-raindrop/ pages & convert them? Does it change them page by page? Does it only update new ones? My preference is going through all & updating them. We should be able to do the same update action if you change other config options, like (in the future) the page namespace prefix (from "logseq-raindrop/" to "raindrop/" or whatever).

**Comment by feigaoxyz** [comment]
I'd prefer using same tags on both side, i.e. #work in Raindrop to [[work]] in Logseq. I don't want to maintain two system of tags and configure/edit back-and-forth. One thing makes it possible is raindrop does support multi-word tag such as `#hello world`.

As the naming, I do prefer the standard `tags::` as I can associate Raindrop data to my Logseq data through these tags -- I tag one link in Raindrop with `#Logseq` and import, I should be able to see relevant pages/blocks in my graph with [[Logseq]]. This is also the reason for above that I prefer to keep the tags exact.

**Comment by phildenhoff** [comment]
I had no idea Logseq had built in support for `tags::`! that makes the choice a lot easier.

I think I agree with you on keepings tags identical across Logseq & Raindrop. I can't think of a reason why you would import a page from Raindrop that you recently tagged and then be surprised / upset that the tags were imported.

Potentially it would be useful to have a filter for tags you never want to import — things used only to organize Raindrops, but that's something we could add later, if requested
