### ISSUE TITLE
Cannot disable adding `annotation-id`

### ISSUE THREAD

**Issue by Yoqazij** [phildenhoff/logseq-raindrop#15]
I would like to work my highlights as easy as possible. Right now I first need to delete all the id's to have a "pure" text import and rename every page.

**Comment by phildenhoff** [comment]
Do you ever re-sync your annotations from Raindrop? Without those IDs, the plug-in would either

- Not sync new content (unless the page was deleted), or
- Add all annotations on Raindrop, potentially duplicating some

**Comment by phildenhoff** [comment]
I'm open to PRs in the future that add this, but atm it's out-of-scope. If you want to hide the annotation IDs, use single page imports.
