### ISSUE TITLE
Import highlights in a journal page

### ISSUE THREAD

**Issue by ConstantinosM** [phildenhoff/logseq-raindrop#24]
Thank you for this very useful plugin! I was wondering if it is possible to import highlights on a journal page or anywhere else without needing to import the bookmark as a page? By the way I do understand that probably this logic won't work with re-sync functionality but I am fine with it.

**Comment by phildenhoff** [comment]
At the moment, no. How would you want that to work?

It's not something I had considered and my initial response is that's out of scope — it's easy enough to copy/reference the annotations to your daily notes.

Another option, if you'd like to see which day you annotated something, might be for the plug-in to automatically tag each annotation with the date it was created/updated. Would that work?

**Comment by ConstantinosM** [comment]
Thank you for your reply! I use Raindrop to bookmark, highlight everything from the internet. Raindrop as you know has its own tags and organization system. I would like to be able to link captured content from Raindrop to pages I have in Logseq. So for example I would like to import, from a raindrop bookmark, highlights in a page   that discusses a specific topic . Or even import bookmarked material with their description and tags from raindrop to logseq as a block and use it as resources for a topic. Personally, I wouldn't be interested on the day that I annotated something, instead I would be interested in the context and if I can link it with other pages I have without necessarily importing it as a whole page. If I can maintain the tags would be awesome as well (for me 😅).

**Comment by phildenhoff** [comment]
Gotcha — I don't think importing specific highlights from a Raindrop is anything I'd like to support at this point. I think the best way to support your workflow is to use queries within Logseq & the existing import workflow within the plugin. As far as I know, there's not a great way to ask Raindrop for "highlights that discuss this topic on pages with that tag" — but Logseq is great at that.

Let me know if you have any other feature requests!
