### ISSUE TITLE
Link to cached copy stored by Raindrop

### ISSUE THREAD

**Issue by jmuchovej** [phildenhoff/logseq-raindrop#28]
👋 Thanks for building this! I've been making some pretty good use of it, so far. 🙂 

I'm curious if you're open to a PR that links to Raindrop's "Permanent Copy". From what I can tell, even though it takes a few minutes/hours to generate, the means of access is the same. That is, Raindrop always sets the redirect to the "Permanent Copy" to... `https://api.raindrop.io/v1/raindrop/<raindrop-id>/cache`.

Would it be possible to link to this copy, as a backup, since some folks (accidentally) remove things we bookmark?

("Permanent Copies" are a paid feature, so maybe this isn't applicable for folks that don't pay for Raindrop, but I imagine this could be an opt-in toggle or something similar?)

**Comment by phildenhoff** [comment]
A link to the permanent copy is a great idea! If you'd like to build the feature, I'm open to a PR :)

A few questions to think about:

- What happens when the cached copy isn't there?
  - What do users see?
  - How (if at all) do we tell them that the cached copy isn't available?
- Is it worth only adding permanent copy links for pages that already have it?
  - How do we update that later when a cached copy is added? Is there a list of "recently cached"?
- What is a good Logseq property name?
  - The current pattern is `raindrop-x` — so... `raindrop-cache:`? `raindrop-archive-url`? `raindrop-permanent-copy`?

And a few thoughts on how I would do this:

- I expect most users who are tying Logseq & Raindrop together are paying for Raindrop, but not all. I would add the tag by default, but add a setting to allow users to disable it.
  - Another option would be to disable all paid features, but frankly I'm not sure if the plugin already uses paid-only features, so that might require some rejigging.

**Comment by jmuchovej** [comment]
**Re:thoughts:** Based on the [Raindrop docs][raindrop-docs], annotations (highlights + notes) are a premium feature, but **highlights are free**. So it seems that not all of `logseq-raindrop`'s features are locked behind "Raindrop Premium", but the greatest value of the plugin comes with "Raindrop Premium".

**Aside:** Generally, there seem to be two ways to refer to the "Permanent copy":
1. `https://api.raindrop.io/rest/v1/raindrop/<raindrop-id>/cache` or...
2. the URL returned from `GET https://api.raindrop.io/rest/v1/raindrop/<raindrop-id>/cache`

The former, I imagine, proxies through Raindrop while the latter is just a plain unauthenticated redirect. (From my own playing around, the latter URL completely lacks authorization, but that's always subject to change, whereas the former URL forces the user through Raindrop – thus, I think the former is the "safest" URL to direct users to (it also happens to be the shortest).)

**Re:questions:** To my knowledge, permanent copies are **always generated**, so long as the user has Raindrop Premium (and it doesn't fail in the limited cases). Additionally, cached copies are primarily useful when the live copy isn't available (or maybe if the site presentation has drastically changed), so I would [naively] expect users not to want/need access to the cached copy until hours (or days) after they add it, at which point it's likely to be there. (Anyone who adds a site to Raindrop expecting an instant cache is misinformed ([the docs state this process takes some time][docs-cache-time]).

That page also points out known limitations, which pushes me towards defaulting to putting the URL, then on the next update we check that it's valid and inform the user if it isn't – that is, we put the `api.raindrop.io/...` URL, then when the user updates the page, we check that the cache was successfully made, if not – we set the property to some text like... `Raindrop failed to make a permanent copy.` (Then maybe point to where they could get help, but I dunno where that would go off-the-cuff.)

From what I could find, there doesn't seem to be a "recently cached" list of any kind, but there's an API endpoint to get URL (2), which I think should function as a good check for "was the page successfully cached?".

> What is a good Logseq property name?

I think `raindrop-cache` is the most succinct, but I'm not sure how "niche" `cache` is compared to the most plainly descriptive `permanent-copy` (since that also follows Raindrop's nomenclature). I'm not too picky about this, but my gut reaction (and how I've been doing this, is with `raindrop-cache`).

[raindrop-docs]: https://help.raindrop.io/premium-features/
[docs-cache-time]: https://help.raindrop.io/backups#permanent-library

**Comment by jmuchovej** [comment]
> Maybe it's worth putting some text with the `disable-cached-urls` setting that the copies take some time to generate?

Just making sure we're thinking of the same thing, in the plugin's settings page, the checkbox for `disable-cached-urls` should mention something like...

```
Raindrop's "Permanent Copy" make take time to generate (typically 20-30 minutes, but sometimes longer).
```

**Also, do you have any qualms with the setting being `enable-cached-urls` and defaulting to checked?** (This is mostly a UX thing, I've usually found people more easily reason about checkbox + enable vs checkbox + disable.)

> It looks like [Raindrops have a cache-status enum](https://developer.raindrop.io/v1/raindrops#other-fields) ...

OOH. This is far more useful than having to do our own testing. 😄

> Yeah, I strongly prefer `raindrop-cache` as well, but I when I search "raindrop cache" I get boring technical documents that _do_ link back to Raindrop, however, when I search "raindrop permanent copy" I get linked straight to the Raindrop backups doc you linked above. It's not my favourite, but I would prefer to use their terminology.

Hmmm... interesting. Running through `raindrop cache` and `raindrop permanent copy`, on:
- Brave – the top result for both is the [feature request on Canny][canny]
- DuckDuckGo – `cache` returns the feature request as top-hit (but initially searched for "raindrop cake") and `perm copy`'s top-hit is the [backups doc][backups].
- Google – returns the feature request for both.
- Bing – does it's usually thing. Though `perm copy` puts the [backups doc][backups] in the top 2.

[canny]: https://raindropio.canny.io/feature-requests/p/ability-to-cache-websites
[backups]: https://help.raindrop.io/backups/

(I mainly went through this for N=2 and b/c I strongly prefer `raindrop-cache` to `raindrop-permanent-copy` 😅 BUT I also agree that `raindrop-permanent-copy` is most likely to point to the [backups doc][backups].) So let's go with `raindrop-permanent-copy`? UNLESS this should also be a setting? (i.e., we permit a different `raindrop-<suffix>` (but that could be addressed later if enough folks find the tag too long).

**Comment by phildenhoff** [comment]
> Just making sure we're thinking of the same thing

We are, that looks excellent 💯 (although "make" → "may")

Using the affirmative (`enable-`) and checking it by default makes perfect sense to me. I can't imagine why we wouldn't want to not have a double negative 🤪 

Based on your search results (I only tried Kagi), I'm fine with either term for the property name. It's up to you. However, I do _not_ think the name of the property should be configurable — allowing that will put us into a mess where some properties are "raindrop-X" and some are "raindrop-Y" but they mean the same thing, or a user changed the value to be "raindrop-id" and now everything is messed up. There's just no benefit to getting into that territory.

**Comment by jmuchovej** [comment]
So, playing around with the Raindrop API – on raindrops with a cache, there's a `cache` key in the response. On newly created raindrops (where no cache exists), a the `cache` key is missing. It seems that `cache.status == "ready"` indicates an existing cache (sanity check). (I'm still waiting on the cache to be made to see what changes, so I'll loop back once it happens.)

One thing that's unclear is whether the `cache` key will show up for _all_ folks, even those without Raindrop Premium. So I guess this begs a question of... what should we do if there's no `cache` key, **but** it's been more than (say) 24 hours?

There are at least two timestamps (`created` and `lastUpdated`) we could check against, but the time limit is rather arbitrary and in the case of [something like this][raindrop-tweet-overload] (where 500K raindrops were added and backlogged other users), that time limit might not be long enough. 

To be fair, this question is mostly centered around providing useful, specific, feedback on what's going on. We could take the path-of-least-resistance and just have two states: (1) Put the `api.raindrop.io/.../cache` URL and (2) text like `Raindrop does not have a Permanent Copy of this website.` **OR** we could provide specific error messages like...

```ts
let cacheMsg: string = ""
switch (r.cache?.status) {
  case "ready":
    cacheMsg = `https://api.raindrop.io/v1/raindrop/${r.id}/cache`;
    break;
  case "retry":
    cacheMsg = "Raindrop is re-attempting to make a Permanent Copy.";
    break;
  case "failed":
  case "invalid-origin":
  case "invalid-timeout":
  case "invalid-size":
    cacheMsg = "Raindrop could not make a Permanent Copy.";
    break;                 
  default:                           
    // This could honestly get rather hairy, since this statement is false for folks
    //   without Raindrop Premium. (A naive test would be the `created` or `lastUpdated` 
    //   keys, but c.f. above for why that might not always be reliable.)
    cacheMsg = "Raindrop appears to be processing this Permanent Copy, please standby.";
    break;                                                                                                                                         
}
```
[raindrop-tweet-overload]: https://twitter.com/raindrop_io/status/1237065641271713795?s=20

**Comment by phildenhoff** [comment]
Thanks for the detailed run-down — I hear what you're saying about providing specific messages, especially for free users of Raindrop.

Frankly, this plugin is pretty simple in terms of architecture. If we wanted to provide better UX for free users or detect and define behaviour for Raindrop's services being overloaded, or really do anything more complex in terms of behaviour, I'd want to restructure the plugin. It just doesn't really support that kind of thing right now.

_For now_, unless folks provide feedback otherwise, I think your path-of-least-resistance strategy is the best. We provide an improvement for users relatively quickly, even if it's small. It doesn't need to be perfect, we can iterate on it.

**Comment by phildenhoff** [comment]
done in https://github.com/phildenhoff/logseq-raindrop/commit/15be215cab7d844dc34e085fe457fd93adfa357f for single-page imports
