### ISSUE TITLE
Adding {color} to highlight template does not work

### ISSUE THREAD

**Issue by aforank** [phildenhoff/logseq-raindrop#30]
I modified the highlight template like this

![image](https://user-images.githubusercontent.com/19813442/225890352-6d6a87cb-8e3c-43ee-8d3f-4ae406c11616.png)

and the result is

![image](https://user-images.githubusercontent.com/19813442/225890565-c78f6295-b84d-4c6a-bd6f-92cc9a90a9e0.png)

Is there anything else I have to do? or is a bug

I would like to use `{color}` something like this, so it literally highlights that.

[[#{color}]]==Highlight==

**Comment by phildenhoff** [comment]
Unfortunately, I'm at the mercy of Logseq here, and I don't think they allow you to highlight a block quote using different colours.

I'll remove the documentation about using `{color}`. If you can find a way to highlight a block quote, let me know, and we can add that in.
