### ISSUE TITLE
Toolbar icon is too similar to Logseq Sync (alternative icon attached)

### ISSUE THREAD

**Issue by flegfleg** [phildenhoff/logseq-raindrop#43]
Hi, thanks for the great plugin! 

Since i installed Logseq sync, my toolbar looks a bit messy, 2 times the same icon in different sizes:
![CleanShot 2023-04-26 at 00 33 58@2x](https://user-images.githubusercontent.com/4009931/234419413-ff523d11-364b-4fc0-b7be-40ea186bafe2.jpg)

Here's an icon i created of the Raindrop Logo in the toolbar style, preview here:

![Preview](https://user-images.githubusercontent.com/4009931/234419503-6eecda51-4a76-4560-8033-d503f826645a.png)

This is the svg, it would be great if you could use it. 
![Icon-Raindrop-1color](https://user-images.githubusercontent.com/4009931/234419666-9c87e9e0-f8c7-4f69-a60f-5dd5510a7178.svg)

 Best!

**Comment by phildenhoff** [comment]
Good point, I've updated the app (v0.2.1) to use the logo you provided. Thanks for including it!
