### ISSUE TITLE
Single Page Imports doesn't work

### ISSUE THREAD

**Issue by AlexPeregudov** [phildenhoff/logseq-raindrop#67]
Single Page Imports doesn't work.
After enabling the option, nothing happens when you click on the icon. In the upper right corner of LogSeq it says "Loading your theme..." 
Tested on the built-in theme, on third-party themes.

**Comment by phildenhoff** [comment]
- Does the plugin work without enabling single page imports?
- Do you have a preferred "Theme mode" set in Logseq's settings? The screen would look like this:

![image](https://github.com/phildenhoff/logseq-raindrop/assets/17505728/5d7c65f0-f421-48e8-9ca0-0d0aeb62d58d)

- After enabling single page imports, did you reload the plugin? Close and open Logseq?
- If you open the Developer Tools (macOS: Option + Command + I) are there any red error messages that _appear_ related to `logseq-raindrop`?

**Comment by AlexPeregudov** [comment]
Thank You. After "dancing" with various settings now all ok. I'll try on clean LogSeq installation.  
Some questions and future requests:
1. Would it be possible to keep folders structure from RainDrop? 
2. How can I keep all bookmarks but separate page for each? I have about 3k bookmarks, LS freezing on it in one page :)

**Comment by phildenhoff** [comment]
Sorry to get back to you so late @AlexPeregudov. Interesting ideas! What does it look like to you to keep the folder/collection structure from Raindrop in Logseq?

- If you want to tag imports with the name of collection, that's definitely a possible feature!
- If you want to put the name of the collection in the page name of multi-page imports (e.g. a page would be called "Raindrop/Podcasts/Radiolab"), that's possible, but I think a bit confusing, especially if you rename the collection in Raindrop.

For your second question, if you want to keep all your bookmarks on separate pages, I don't think you want to use single-page imports. Single-page import is for when you want one page "Raindrop" that includes all the pages you've saved to Raindrop. Multi-page import is for when you want one page per imported raindrop, possibly all nested under a namespace.

**Comment by ashtyn3** [comment]
I am getting the same error message, "loading theme..."
