### ISSUE TITLE
Support for org-mode

### ISSUE THREAD

**Issue by choffee** [phildenhoff/logseq-raindrop#70]
Currently all the templates default to markdown. It would be good if it could spot I'm using org-mode and swap to using that.

I have a template for inserting them but I can't see how to change the "Added to raindop" template.

```
[[{{{url}}}][{{{title}}}]]
:PROPERTIES:
:title: {{{title}}}
:url: {{{url}}}
:Tags: {{{tags}}}
:date-saved: [[{{{dateCreated}}}]]
:last-updated: [[{{{dateUpdated}}}]]
:END:
```

**Comment by phildenhoff** [comment]
Ahh yes, I forgot org mode was an option! I've only used Markdown myself. Good suggestions :)

**Comment by phildenhoff** [comment]
Do you have any recommendations for what you want in the default the "Added to Raindrop" template?

This is what I have at the moment, but I'm finding that the URLs that have slashes in them suddenly have italics... and the recommended way to prevent that is to include zero-width space characters, which I'd prefer not to do as that will likely break the URL if it's copied + pasted.

```org
Saved to Raindrop:
{{#links}}
[[{{{raindropPreviewUrl}}}][{{{savedUrl}}} (Raindrop preview)]]
{{/links}}
```

I'm thinking of putting `{{{savedUrl}}}` as an in-line codeblock, but that looks like this in Logseq:

![image](https://github.com/phildenhoff/logseq-raindrop/assets/17505728/5db265ec-80e9-452e-b706-fe92de39d50a)

which isn't the best
